version: '3.9'

services:
  sell-car-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sell_car
    volumes:
      - sell_car_project:/var/lib/postgresql/sell_car
volumes:
  sell_car_project: